//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIChrysallis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localitats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public localitats()
        {
            this.socis = new HashSet<socis>();
            this.esdeveniments = new HashSet<esdeveniments>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int id_provincia { get; set; }
    
        public virtual provincies provincies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<socis> socis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<esdeveniments> esdeveniments { get; set; }
    }
}
