//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIChrysallis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menors_socis
    {
        public int id_soci { get; set; }
        public int id_menor { get; set; }
        public string relacio { get; set; }
    
        public virtual menors menors { get; set; }
        public virtual socis socis { get; set; }
    }
}
