//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIChrysallis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CHRYSALLISEntities : DbContext
    {
        public CHRYSALLISEntities()
            : base("name=CHRYSALLISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assistir> assistir { get; set; }
        public virtual DbSet<comunitats> comunitats { get; set; }
        public virtual DbSet<documents> documents { get; set; }
        public virtual DbSet<localitats> localitats { get; set; }
        public virtual DbSet<menors> menors { get; set; }
        public virtual DbSet<menors_socis> menors_socis { get; set; }
        public virtual DbSet<provincies> provincies { get; set; }
        public virtual DbSet<rols> rols { get; set; }
        public virtual DbSet<socis> socis { get; set; }
        public virtual DbSet<valoracions> valoracions { get; set; }
        public virtual DbSet<esdeveniments> esdeveniments { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<usuaris> usuaris { get; set; }
    }
}
