//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIChrysallis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuaris
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuaris()
        {
            this.comunitats = new HashSet<comunitats>();
        }
    
        public int id { get; set; }
        public string contrasenya { get; set; }
        public int id_rol { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public Nullable<int> id_socio { get; set; }
        public bool actiu { get; set; }
    
        public virtual rols rols { get; set; }
        public virtual socis socis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comunitats> comunitats { get; set; }
    }
}
